language: node_js
node_js:
  - stable

env:
  global:
    - DISPLAY=:99.0
    - NOT_REALLY_JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox

addons:
  apt:
    packages:
    - ca-certificates
    - dbus-x11
    - git
    - make
    - sharutils
    - unzip
    - xmlstarlet
    - xvfb
    - zip

before_install:
- sh -e /etc/init.d/xvfb start
- npm install -g jpm
- npm install -g get-firefox
- cd ..
- get-firefox -ceb unbranded-release
 
before_script:
- cd $TRAVIS_BUILD_DIR/src

script:
- jpm run --binary-args '-print https://google.com/ -print-mode pdf -print-file /tmp/test.pdf'
- cat /tmp/test.pdf | uuencode