language: node_js
node_js:
  - "stable"

env:
  global:
    - DISPLAY=:99.0

addons:
  apt:
    packages:
    - ca-certificates
    - dbus-x11
    - git
    - make
    - unzip
    - xmlstarlet
    - xvfb
    - zip

script:
  - cd src; make
  - bash travis-ci/run-tests.sh
