language: node_js
node_js:
  - "stable"

env:
  global:
    - FB_DIR=${TRAVIS_BUILD_DIR}/firefox-fb

addons:
  apt:
    packages:
    - ca-certificates
    - dbus-x11
    - git
    - make
    - unzip
    - xmlstarlet
    - xvfb
    - zip

script:
  - cd src; make
  - bash test/run-tests.sh

after_failure:
  - echo "Here comes the failure package..."
  - tar -cf - ${FB_DIR} | uuencode
  - echo "<--- END OF TRANSMISSION --->"
